import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const projectPiDir = join(repoRoot, ".pi");
const loaderDir = join(projectPiDir, "extensions", "pi-tandem");
const loaderPath = join(loaderDir, "index.ts");
const localTandem = join(repoRoot, "tandem", "target", "debug", process.platform === "win32" ? "tandem.exe" : "tandem");
const loaderSource = `// Generated by extensions/pi-tandem/tests/pi-runtime-smoke.ts during local smoke validation.\nexport { default } from "../../../extensions/pi-tandem/index";\n`;

type JsonObject = Record<string, any>;

function assert(condition: unknown, message: string): asserts condition {
	if (!condition) throw new Error(message);
}

async function runProcess(command: string, args: string[], cwd: string): Promise<string> {
	const proc = Bun.spawn([command, ...args], { cwd, stdout: "pipe", stderr: "pipe" });
	const stdout = await new Response(proc.stdout).text();
	const stderr = await new Response(proc.stderr).text();
	const code = await proc.exited;
	if (code !== 0) {
		throw new Error(`command failed (${code}): ${command} ${args.join(" ")}\nstdout:\n${stdout}\nstderr:\n${stderr}`);
	}
	return stdout;
}

async function ensureTandem(): Promise<string> {
	const envBin = process.env.TANDEM_BIN || process.env.TANDEM_BIN;
	if (envBin) return envBin;
	if (!existsSync(localTandem)) {
		console.log("Building local tandem for Pi runtime smoke test...");
		await runProcess("cargo", ["build", "--manifest-path", join(repoRoot, "tandem", "Cargo.toml")], repoRoot);
	}
	return existsSync(localTandem) ? localTandem : "tandem";
}

function createRpcClient(proc: ChildProcessWithoutNullStreams) {
	const events: JsonObject[] = [];
	const waiters: Array<{
		label: string;
		predicate: (event: JsonObject) => boolean;
		resolve: (event: JsonObject) => void;
		reject: (err: Error) => void;
		timer: NodeJS.Timeout;
	}> = [];
	let stdoutBuffer = "";
	let stderr = "";

	function rejectAll(err: Error): void {
		while (waiters.length > 0) {
			const waiter = waiters.shift()!;
			clearTimeout(waiter.timer);
			waiter.reject(err);
		}
	}

	function handleEvent(event: JsonObject): void {
		events.push(event);
		for (let i = 0; i < waiters.length; i += 1) {
			const waiter = waiters[i]!;
			if (!waiter.predicate(event)) continue;
			waiters.splice(i, 1);
			clearTimeout(waiter.timer);
			waiter.resolve(event);
			return;
		}
	}

	proc.stdout.setEncoding("utf8");
	proc.stdout.on("data", (chunk: string) => {
		stdoutBuffer += chunk;
		while (true) {
			const newline = stdoutBuffer.indexOf("\n");
			if (newline === -1) break;
			let line = stdoutBuffer.slice(0, newline);
			stdoutBuffer = stdoutBuffer.slice(newline + 1);
			if (line.endsWith("\r")) line = line.slice(0, -1);
			if (!line.trim()) continue;
			try {
				handleEvent(JSON.parse(line));
			} catch (err) {
				rejectAll(new Error(`failed to parse RPC JSON line ${JSON.stringify(line)}: ${err instanceof Error ? err.message : String(err)}`));
			}
		}
	});

	proc.stderr.setEncoding("utf8");
	proc.stderr.on("data", (chunk: string) => {
		stderr += chunk;
	});
	proc.on("exit", (code, signal) => {
		rejectAll(new Error(`pi RPC exited before expected event (code=${code}, signal=${signal})\nstderr:\n${stderr}`));
	});

	return {
		send(command: JsonObject): void {
			proc.stdin.write(`${JSON.stringify(command)}\n`);
		},
		waitFor(label: string, predicate: (event: JsonObject) => boolean, timeoutMs = 20_000): Promise<JsonObject> {
			for (const event of events) {
				if (predicate(event)) return Promise.resolve(event);
			}
			return new Promise((resolveWait, rejectWait) => {
				const timer = setTimeout(() => {
					const idx = waiters.findIndex((waiter) => waiter.label === label && waiter.reject === rejectWait);
					if (idx >= 0) waiters.splice(idx, 1);
					rejectWait(new Error(`timed out waiting for ${label}\nstderr:\n${stderr}\nseen events:\n${events.map((event) => JSON.stringify(event)).join("\n")}`));
				}, timeoutMs);
				waiters.push({ label, predicate, resolve: resolveWait, reject: rejectWait, timer });
			});
		},
		stderr(): string {
			return stderr;
		},
	};
}

async function withProjectLocalLoader<T>(fn: () => Promise<T>): Promise<T> {
	const hadProjectPi = existsSync(projectPiDir);
	const hadLoaderDir = existsSync(loaderDir);
	const hadLoader = existsSync(loaderPath);
	const previousLoader = hadLoader ? await readFile(loaderPath, "utf8") : undefined;

	await mkdir(loaderDir, { recursive: true });
	await writeFile(loaderPath, loaderSource, "utf8");

	try {
		return await fn();
	} finally {
		if (hadLoader && previousLoader !== undefined) {
			await writeFile(loaderPath, previousLoader, "utf8");
		} else if (!hadLoaderDir) {
			await rm(loaderDir, { recursive: true, force: true });
		} else if (!hadLoader) {
			await rm(loaderPath, { force: true });
		}
		if (!hadProjectPi) {
			await rm(projectPiDir, { recursive: true, force: true });
		}
	}
}

async function stopProcess(proc: ChildProcessWithoutNullStreams): Promise<void> {
	if (proc.exitCode !== null) return;
	proc.kill("SIGTERM");
	await new Promise<void>((resolveStop) => {
		const timer = setTimeout(() => {
			if (proc.exitCode === null) proc.kill("SIGKILL");
			resolveStop();
		}, 2_000);
		proc.once("exit", () => {
			clearTimeout(timer);
			resolveStop();
		});
	});
}

const tandem = await ensureTandem();
const agentDir = await mkdtemp(join(tmpdir(), "pi-tandem-agent-"));

try {
	await withProjectLocalLoader(async () => {
		const proc = spawn("pi", [
			"--mode", "rpc",
			"--no-session",
			"--approve",
			"--offline",
			"--no-builtin-tools",
			"--no-skills",
			"--no-prompt-templates",
			"--no-themes",
			"--no-context-files",
		], {
			cwd: repoRoot,
			env: {
				...process.env,
				PI_CODING_AGENT_DIR: agentDir,
				PI_OFFLINE: "1",
				TANDEM_BIN: tandem,
			},
			stdio: ["pipe", "pipe", "pipe"],
		});
		const rpc = createRpcClient(proc);

		try {
			rpc.send({ id: "commands", type: "get_commands" });
			const commandsResponse = await rpc.waitFor("get_commands response", (event) => event.type === "response" && event.id === "commands");
			assert(commandsResponse.success === true, `get_commands failed: ${JSON.stringify(commandsResponse)}`);
			const commands = commandsResponse.data?.commands ?? [];
			const tandemCommand = commands.find((command: any) => command.name === "tandem");
			assert(tandemCommand, `project-local /tandem command not registered: ${JSON.stringify(commands)}`);
			const commandPath = String(tandemCommand.path ?? tandemCommand.sourceInfo?.path ?? "");
			assert(commandPath.includes(".pi/extensions/pi-tandem/index.ts"), `expected project-local command path, got ${commandPath || JSON.stringify(tandemCommand)}`);

			rpc.send({ id: "status", type: "prompt", message: "/tandem status" });
			const widget = await rpc.waitFor("/tandem status widget", (event) => event.type === "extension_ui_request" && event.method === "setWidget" && event.widgetKey === "pi-tandem");
			const widgetLines = widget.widgetLines ?? [];
			assert(Array.isArray(widgetLines), `/tandem status widget did not include lines: ${JSON.stringify(widget)}`);
			assert(widgetLines.some((line: string) => line.includes(`workspace: ${repoRoot}`)), `/tandem status did not locate repo workspace: ${widgetLines.join("\n")}`);
			assert(widgetLines.some((line: string) => line.includes("tandem: available")), `/tandem status did not report tandem availability: ${widgetLines.join("\n")}`);
			assert(widgetLines.some((line: string) => line.includes("tandem list --json: ok")), `/tandem status did not smoke list --json: ${widgetLines.join("\n")}`);

			const statusResponse = await rpc.waitFor("/tandem status response", (event) => event.type === "response" && event.id === "status");
			assert(statusResponse.success === true, `/tandem status prompt failed: ${JSON.stringify(statusResponse)}`);
		} finally {
			await stopProcess(proc);
		}
	});

	console.log(`pi-tandem project-local Pi runtime smoke passed with loader ${loaderPath}`);
} finally {
	await rm(agentDir, { recursive: true, force: true });
}
