import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildAccordArgs, buildDecisionArgs, buildInitArgs, buildLogArgs, buildPapercutArgs, buildRulesArgs, buildSearchArgs, buildTaskArgs, ACCORD_ACTIONS, tandemTaskParameters } from "../index";
const bin = process.env.TANDEM_BIN ?? "tandem";
const assert = (v: unknown, m: string): asserts v => { if (!v) throw new Error(m); };
const run = async (args: string[], cwd: string) => { const p = Bun.spawn([bin, ...args], { cwd, stdout: "pipe", stderr: "pipe" }); const out = await new Response(p.stdout).text(); const err = await new Response(p.stderr).text(); if (await p.exited) throw new Error(`${args.join(" ")}\n${out}\n${err}`); return out; };
const json = (s: string) => JSON.parse(s.trim());
const id = (s: string) => { const m = /^ID:\s+(\S+)/m.exec(s); assert(m, `missing ID in ${s}`); return m[1]; };
assert(!(tandemTaskParameters as any).properties.move, "task schema must not expose move");
assert(JSON.stringify(ACCORD_ACTIONS) === JSON.stringify(["claim", "deliver", "rework", "block", "resume", "release", "fail"]), "accord actions must match 0.3");
assert(buildInitArgs({ title: "x" }).join(" ") === "init --title x", "init argv");
assert(buildTaskArgs({ action: "list", tags: ["a", "b"], decisionStatus: "accepted", resolution: "c" }).join(" ") === "list --tag a --tag b --decision-status accepted --resolution c --json", "list argv");
assert(buildTaskArgs({ action: "add", title: "x", acceptance: ["done"] }).join(" ") === "add task x --acceptance done --json", "add argv");
assert(buildTaskArgs({ action: "cancel", id: "task-1", reason: "no longer needed" }).join(" ") === "cancel task-1 --note no longer needed --json", "cancel argv");
assert(buildTaskArgs({ action: "complete", id: "task-1" }).join(" ") === "complete task-1 --json", "complete argv");
assert(buildAccordArgs({ action: "deliver", id: "task-1", summary: "done", evidence: ["test"], filesChanged: ["x"] }).join(" ") === "accord deliver task-1 --summary done --evidence test --file-changed x --json", "accord argv");
assert(buildLogArgs({ action: "list" }).join(" ") === "list --scope archived --json", "log argv");
assert(buildDecisionArgs({ action: "list" }).join(" ") === "list --type decision --json", "decision argv");
assert(buildSearchArgs({ query: "x", tags: ["a"], limit: 2 }).join(" ") === "search x --tag a --limit 2 --json", "search argv");
assert(buildPapercutArgs({ action: "add", title: "friction", body: "criterion" }).join(" ") === "add task friction --acceptance criterion --tag papercut --priority low", "papercut argv");
const ws = await mkdtemp(join(tmpdir(), "pi-tandem-smoke-"));
try {
 await run(buildInitArgs({ title: "Smoke" }), ws);
 const added = json(await run(buildTaskArgs({ action: "add", title: "Smoke task", acceptance: ["works"], tags: ["smoke"] }), ws)); assert(added.ok && added.data.id, "add envelope"); const task = added.data.id;
 const listed = json(await run(buildTaskArgs({ action: "list" }), ws)); assert(listed.ok && listed.data.some((x: any) => x.id === task), "list envelope");
 const shown = json(await run(buildTaskArgs({ action: "show", id: task }), ws)); assert(shown.ok && shown.data.id === task, "show envelope");
 const accord = json(await run(buildAccordArgs({ action: "claim", id: task, assignee: "smoke" }), ws)); assert(accord.ok && accord.data.event, "accord envelope");
 const rule = json(await run(buildRulesArgs({ action: "add", category: "always", rule: "Smoke" }), ws)); assert(rule.ok && rule.data.id === "always-1", "rules envelope");
 const decision = json(await run(buildDecisionArgs({ action: "add", title: "Choice" }), ws)); assert(decision.ok && decision.data.id, "decision envelope");
 const paper = json(await run(buildTaskArgs({ action: "add", title: "Paper", acceptance: ["criterion"], tags: ["papercut"], priority: "low" }), ws)); assert(paper.ok, "papercut task");
 const search = json(await run(buildSearchArgs({ query: "Smoke" }), ws)); assert(search.ok && Array.isArray(search.data), "search envelope");
 const completed = json(await run(buildTaskArgs({ action: "complete", id: task }), ws)); assert(completed.ok && completed.data.id === task, "completion archive envelope");
 const logs = json(await run(buildLogArgs({ action: "list" }), ws)); assert(logs.ok && logs.data.some((x: any) => x.id === task), "log list envelope");
 console.log("pi-tandem smoke passed (16 assertions)");
} finally { await rm(ws, { recursive: true, force: true }); }
