#!/bin/sh
# Tandem branded installer redirect shim.
#
# The canonical installer is generated by cargo-dist and published on the
# latest GitHub Release as tandem-installer.sh. Keep this file intentionally
# small: it only forwards execution to that generated installer so cargo-dist
# remains the source of truth for OS/architecture detection, release asset
# selection, and user-local installation behavior.

set -eu

INSTALLER_URL="https://github.com/Algorant/tandem/releases/latest/download/tandem-installer.sh"

if command -v curl >/dev/null 2>&1; then
  exec sh -c 'url=$1; shift; curl --proto "=https" --tlsv1.2 -fsSL "$url" | sh -s -- "$@"' sh "$INSTALLER_URL" "$@"
elif command -v wget >/dev/null 2>&1; then
  exec sh -c 'url=$1; shift; wget -qO- "$url" | sh -s -- "$@"' sh "$INSTALLER_URL" "$@"
else
  echo "error: install requires curl or wget" >&2
  echo "download and run: $INSTALLER_URL" >&2
  exit 1
fi
